In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
b = a.T
print(b)

[1 2 3 4 5]


In [6]:
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [7]:
d = c.T
print(d)

[[1 3]
 [2 4]]


## BROADCASTING

In [8]:
e = np.array([1,2,3])
print(e)
g = e+5
print(g)

[1 2 3]
[6 7 8]


In [9]:
h = np.array([1,2,3])
print(h)
i = h+[1]
print(i)

[1 2 3]
[2 3 4]


In [13]:
j = np.array([[1,2,3],[4,5,6]])
print(j)
z1 = np.array([100])
z2 = j+z1
z2

[[1 2 3]
 [4 5 6]]


array([[101, 102, 103],
       [104, 105, 106]])

In [14]:
j = np.array([[1,2,3],[4,5,6]])
print(j)
z1 = np.array([100,200])
z2 = j+z1
z2

[[1 2 3]
 [4 5 6]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [15]:
j = np.array([[1,2,3],[4,5,6]])
print(j)
z1 = np.array([100,200,300])
z2 = j+z1
z2

[[1 2 3]
 [4 5 6]]


array([[101, 202, 303],
       [104, 205, 306]])

In [19]:
k = j.itemsize
print(k)
l = np.array([1, 2, 3, 4], dtype = float) 
print(l)
print(l.itemsize)

8
[1. 2. 3. 4.]
8


## MATRIX MULTIPLICATION

In [20]:
m = np.array([1,2,3])
n = np.array([4,5,6])
print(m@n)

32


## STATISTICS

In [11]:
o = np.array([[5,13,3],[2,3,4]])

In [35]:
o = np.array([[5,13,3],[2,3,4]])
print(o)
print(o.min())

[[ 5 13  3]
 [ 2  3  4]]
2


In [36]:
o.min()

np.int64(2)

In [37]:
o.max()

np.int64(13)

In [12]:
o.mean()

np.float64(5.0)

In [13]:
o.std()

np.float64(3.696845502136472)

In [6]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [27]:
p = np.array([[35,12,48,60],[50,55,53,56],[28,30,27,29],[45,48,50,47],[60,65,63,66],[33,37,35,34],[49,51,50,48],[29,31,30,32]])
print(p)
print(p.ndim)

[[35 12 48 60]
 [50 55 53 56]
 [28 30 27 29]
 [45 48 50 47]
 [60 65 63 66]
 [33 37 35 34]
 [49 51 50 48]
 [29 31 30 32]]
2


In [32]:
r = np.mean(p, axis=1)
print(r)

[38.75 53.5  28.5  47.5  63.5  34.75 49.5  30.5 ]


In [40]:
for i in range(8):
    check = True
    for j in range(4):
        if(p[i][j]>55):
            check = False
    if(check == True):
        print(p[i])

[28 30 27 29]
[45 48 50 47]
[33 37 35 34]
[49 51 50 48]
[29 31 30 32]


In [49]:
for i in range(8):
    sum = 0
    per = 0
    for j in range(3):
        sum += p[i][j]
        per = (j/3);
    print(sum)
    print(per)
    if p[i][3]>per:
        print(p[i])

95
0.6666666666666666
[35 12 48 60]
158
0.6666666666666666
[50 55 53 56]
85
0.6666666666666666
[28 30 27 29]
143
0.6666666666666666
[45 48 50 47]
188
0.6666666666666666
[60 65 63 66]
105
0.6666666666666666
[33 37 35 34]
150
0.6666666666666666
[49 51 50 48]
90
0.6666666666666666
[29 31 30 32]
